# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: #The branches 
- main
- Production
- QA

pool: #Recomended pool in case you use powershell
  vmImage: windows-latest

steps:

- task: PowerShell@2 #Task to deploy the variable to the tags in the pipeline in order to use it in the Releases
  inputs:
    targetType: 'inline'
    script: 'Write-Host "##vso[build.addbuildtag]$(Build.SourceBranchName)"'    

